from typing import Any, TypeVar, overload
from collections.abc import (
    Mapping,
    MutableMapping,
    Iterable,
    Iterator,
    ItemsView,
    KeysView,
    ValuesView,
)

__all__ = ["FrozenDict", "PyFrozenDict"]

_T_co = TypeVar("_T_co", covariant=True)
_K = TypeVar("_K")
_T = TypeVar("_T")

# NOTE: Other functions that aren't here are defined in collections.abc and in typeshed itself.
class FrozenDict(MutableMapping[_K, _T]):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self: FrozenDict[str, _T], **kwargs: _T) -> None: ...  # pyright: ignore[reportInvalidTypeVarUse]  #11780
    @overload
    def __init__(self, map: Mapping[_K, _T] | Iterable[tuple[_K, _T]], /) -> None: ...
    @overload
    def __init__(
        self: dict[str, _T],  # pyright: ignore[reportInvalidTypeVarUse]  #11780
        map: Mapping[str, _T],
        /,
        **kwargs: _T,
    ) -> None: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def frozen(self) -> bool: ...
    def freeze(self) -> None: ...
    def __getitem__(self, key: _K) -> _T: ...
    def __setitem__(self, key: _K, value: _T) -> None: ...
    def __delitem__(self, key: _K) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_K]: ...
    def __reversed__(self) -> Iterator[_K]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def clear(self) -> None: ...
    def items(self) -> ItemsView[_K, _T]: ...
    def keys(self) -> KeysView[_K]: ...
    def values(self) -> ValuesView[_T]: ...
    @overload
    def update(__map: Mapping[_K, _T], **kwargs: _T) -> None: ...
    @overload
    def update(__map: Iterable[tuple[_K, _T]], **kwargs: _T) -> None: ...
    def update(**kwargs: _T) -> None: ...

PyFrozenDict = FrozenDict
